apiVersion: v1
kind: Pod
metadata:
  name: presto-cli
  namespace: default
spec:
  volumes:
    - name: shared-vol
      persistentVolumeClaim:
        claimName: data-client-share
    - name: hive-catalog
      persistentVolumeClaim:
        claimName: hive-catalog  

  containers:
  - name: presto-cli
    image: "uprush/prestosql-cli:330"
    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
    # Configure a mountpoint for the volume we defined above
    volumeMounts:
      - name: shared-vol
        mountPath: /data
      - name: hive-catalog
        mountPath: /hive_catalog

        
